$(document).ready(function(){
    $("#shipping-company").hide();
    $("#commercial").click(function(){
        $("#shipping-company").show();
    });
    $("#residential").click(function(){
        $("#shipping-company").hide();
    });
});
